### PR TITLE
Supporting website features

### PR DESCRIPTION
**Pull request by Run-Lin**
### What changes were proposed in this pull request?
Supporting website features
Using https://docusaurus.io/docs/installation
Preview the website: https://run-lin.github.io

### Why are the changes needed?
At present there is no website, now need a website to do better publicity, let more people know it

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
No need

### CODE REVIEW

**Comment by jerryshao** [comment]
@colinmjj @jerqi PTAL.

**Comment by roryqi** [comment]
I click the every link. The links are OK. But I can't find the the word of `Incubating` in the https://run-lin.github.io/.

**Comment by colinmjj** [comment]
I check the preview website, LGTM. It's better to have the framework first and do the improvement in the next step.

**Review by roryqi — APPROVED** [review]
LGTM, Agree with @colinmjj , Let's merge this pr first. Thanks @Run-Lin @colinmjj

**Comment by jerryshao** [comment]
I think only merging this PR is not enough, we should build and trigger ASF to deploy the website as a follow-up work @jerqi @colinmjj @Run-Lin .

**Comment by roryqi** [comment]
> I think only merging this PR is not enough, we should build and trigger ASF to deploy the website as a follow-up work @jerqi @colinmjj @Run-Lin .

I have added the deploy workflow in the pr https://github.com/apache/incubator-uniffle-website/pull/2.

**Pull request merged**
